// SYSTEM_GENERATED - DO NOT EDIT MANUALLY
// Generated by backend/src/scripts/generateCampusNetwork.ts
import { ScenarioGraph } from '../types/index';

export const campusNetworkGraph: ScenarioGraph = {
  "nodes": [
    {
      "id": "main_router",
      "label": "Main_Router",
      "type": "building_router",
      "x": 1300,
      "y": 600,
      "level": 0
    },
    {
      "id": "hostel_router",
      "label": "Hostel Router",
      "type": "building_router",
      "x": 800,
      "y": 600,
      "level": 0
    },
    {
      "id": "college_router",
      "label": "College Router",
      "type": "building_router",
      "x": 1800,
      "y": 600,
      "level": 0
    },
    {
      "id": "sw0_server",
      "label": "Sw0",
      "type": "floor_router",
      "x": 1300,
      "y": 450,
      "level": 1
    },
    {
      "id": "s1_hostel",
      "label": "S1",
      "type": "floor_router",
      "x": 650,
      "y": 600,
      "level": 1
    },
    {
      "id": "s0_college",
      "label": "S0",
      "type": "floor_router",
      "x": 2000,
      "y": 600,
      "level": 1
    },
    {
      "id": "server_email",
      "label": "EMAIL",
      "type": "server",
      "x": 1100,
      "y": 300,
      "level": 2
    },
    {
      "id": "server_dns",
      "label": "DNS",
      "type": "server",
      "x": 1300,
      "y": 300,
      "level": 2
    },
    {
      "id": "server_web",
      "label": "WEB",
      "type": "server",
      "x": 1500,
      "y": 300,
      "level": 2
    },
    {
      "id": "ap_boys",
      "label": "Boys Block AP",
      "type": "wireless_ap",
      "x": 500,
      "y": 400,
      "level": 2
    },
    {
      "id": "boys_pc1",
      "label": "PC-PT\n192.168.3.6",
      "type": "access_point",
      "x": 300,
      "y": 200,
      "level": 3
    },
    {
      "id": "boys_lap1",
      "label": "Laptop-PT\n192.168.3.7",
      "type": "access_point",
      "x": 450,
      "y": 150,
      "level": 3
    },
    {
      "id": "boys_lap2",
      "label": "Laptop-PT\n192.168.3.8",
      "type": "access_point",
      "x": 600,
      "y": 150,
      "level": 3
    },
    {
      "id": "boys_smart1",
      "label": "Smartphone\n192.168.3.9",
      "type": "access_point",
      "x": 750,
      "y": 250,
      "level": 3
    },
    {
      "id": "ap_girls",
      "label": "Girls Block AP",
      "type": "wireless_ap",
      "x": 500,
      "y": 800,
      "level": 2
    },
    {
      "id": "girls_pc1",
      "label": "PC-PT\n192.168.3.2",
      "type": "access_point",
      "x": 300,
      "y": 1000,
      "level": 3
    },
    {
      "id": "girls_lap1",
      "label": "Laptop-PT\n192.168.3.3",
      "type": "access_point",
      "x": 450,
      "y": 1050,
      "level": 3
    },
    {
      "id": "girls_lap2",
      "label": "Laptop-PT\n192.168.3.4",
      "type": "access_point",
      "x": 600,
      "y": 1050,
      "level": 3
    },
    {
      "id": "girls_smart1",
      "label": "Smartphone\n192.168.3.5",
      "type": "access_point",
      "x": 750,
      "y": 950,
      "level": 3
    },
    {
      "id": "ap_ab1",
      "label": "AB1 AP",
      "type": "wireless_ap",
      "x": 1850,
      "y": 400,
      "level": 2
    },
    {
      "id": "ab1_pc1",
      "label": "PC-PT\n192.168.1.17",
      "type": "access_point",
      "x": 1650,
      "y": 200,
      "level": 3
    },
    {
      "id": "ab1_lap1",
      "label": "Laptop-PT\n192.168.1.16",
      "type": "access_point",
      "x": 1800,
      "y": 150,
      "level": 3
    },
    {
      "id": "ab1_pc2",
      "label": "PC-PT\n192.168.1.15",
      "type": "access_point",
      "x": 1950,
      "y": 150,
      "level": 3
    },
    {
      "id": "ab1_lap2",
      "label": "Laptop-PT\n192.168.1.14",
      "type": "access_point",
      "x": 2100,
      "y": 250,
      "level": 3
    },
    {
      "id": "ap_ab2",
      "label": "AB2 AP",
      "type": "wireless_ap",
      "x": 2450,
      "y": 400,
      "level": 2
    },
    {
      "id": "ab2_pc1",
      "label": "PC-PT\n192.168.1.13",
      "type": "access_point",
      "x": 2300,
      "y": 250,
      "level": 3
    },
    {
      "id": "ab2_lap1",
      "label": "Laptop-PT\n192.168.1.12",
      "type": "access_point",
      "x": 2450,
      "y": 150,
      "level": 3
    },
    {
      "id": "ab2_pc2",
      "label": "PC-PT\n192.168.1.11",
      "type": "access_point",
      "x": 2600,
      "y": 150,
      "level": 3
    },
    {
      "id": "ab2_lap2",
      "label": "Laptop-PT\n192.168.1.10",
      "type": "access_point",
      "x": 2750,
      "y": 200,
      "level": 3
    },
    {
      "id": "ap_it",
      "label": "IT AP",
      "type": "wireless_ap",
      "x": 1600,
      "y": 800,
      "level": 2
    },
    {
      "id": "it_pc1",
      "label": "PC-PT\n192.168.1.2",
      "type": "access_point",
      "x": 1500,
      "y": 1000,
      "level": 3
    },
    {
      "id": "it_pc2",
      "label": "PC-PT\n192.168.1.3",
      "type": "access_point",
      "x": 1650,
      "y": 1050,
      "level": 3
    },
    {
      "id": "it_lap1",
      "label": "Laptop-PT\n192.168.1.4",
      "type": "access_point",
      "x": 1800,
      "y": 1000,
      "level": 3
    },
    {
      "id": "ap_lib",
      "label": "Lib AP",
      "type": "wireless_ap",
      "x": 2100,
      "y": 800,
      "level": 2
    },
    {
      "id": "lib_pc1",
      "label": "PC-PT\n192.168.1.5",
      "type": "access_point",
      "x": 1950,
      "y": 1050,
      "level": 3
    },
    {
      "id": "lib_pc2",
      "label": "PC-PT\n192.168.1.6",
      "type": "access_point",
      "x": 2200,
      "y": 1050,
      "level": 3
    },
    {
      "id": "ap_dome",
      "label": "Dome Area AP",
      "type": "wireless_ap",
      "x": 2600,
      "y": 800,
      "level": 2
    },
    {
      "id": "dome_lap1",
      "label": "Laptop-PT\n192.168.1.7",
      "type": "access_point",
      "x": 2450,
      "y": 1000,
      "level": 3
    },
    {
      "id": "dome_pc1",
      "label": "PC-PT\n192.168.1.8",
      "type": "access_point",
      "x": 2600,
      "y": 1050,
      "level": 3
    },
    {
      "id": "dome_pc2",
      "label": "PC-PT\n192.168.1.9",
      "type": "access_point",
      "x": 2750,
      "y": 1000,
      "level": 3
    }
  ],
  "edges": [
    {
      "id": "e-main-hostel",
      "from": "main_router",
      "to": "hostel_router",
      "latency": 10,
      "type": "serial"
    },
    {
      "id": "e-main-college",
      "from": "main_router",
      "to": "college_router",
      "latency": 10,
      "type": "serial"
    },
    {
      "id": "e-main-sw0",
      "from": "main_router",
      "to": "sw0_server",
      "latency": 3,
      "type": "copper_straight"
    },
    {
      "id": "e-hostel-s1",
      "from": "hostel_router",
      "to": "s1_hostel",
      "latency": 3,
      "type": "copper_straight"
    },
    {
      "id": "e-college-s0",
      "from": "college_router",
      "to": "s0_college",
      "latency": 3,
      "type": "copper_straight"
    },
    {
      "id": "e-sw0-email",
      "from": "sw0_server",
      "to": "server_email",
      "latency": 2,
      "type": "copper_straight"
    },
    {
      "id": "e-sw0-dns",
      "from": "sw0_server",
      "to": "server_dns",
      "latency": 2,
      "type": "copper_straight"
    },
    {
      "id": "e-sw0-web",
      "from": "sw0_server",
      "to": "server_web",
      "latency": 2,
      "type": "copper_straight"
    },
    {
      "id": "e-s1-ap_boys",
      "from": "s1_hostel",
      "to": "ap_boys",
      "latency": 2,
      "type": "copper_straight"
    },
    {
      "id": "e-ap_boys-1",
      "from": "ap_boys",
      "to": "boys_pc1",
      "latency": 5,
      "type": "wireless"
    },
    {
      "id": "e-ap_boys-2",
      "from": "ap_boys",
      "to": "boys_lap1",
      "latency": 5,
      "type": "wireless"
    },
    {
      "id": "e-ap_boys-3",
      "from": "ap_boys",
      "to": "boys_lap2",
      "latency": 5,
      "type": "wireless"
    },
    {
      "id": "e-ap_boys-4",
      "from": "ap_boys",
      "to": "boys_smart1",
      "latency": 5,
      "type": "wireless"
    },
    {
      "id": "e-s1-ap_girls",
      "from": "s1_hostel",
      "to": "ap_girls",
      "latency": 2,
      "type": "copper_straight"
    },
    {
      "id": "e-ap_girls-1",
      "from": "ap_girls",
      "to": "girls_pc1",
      "latency": 5,
      "type": "wireless"
    },
    {
      "id": "e-ap_girls-2",
      "from": "ap_girls",
      "to": "girls_lap1",
      "latency": 5,
      "type": "wireless"
    },
    {
      "id": "e-ap_girls-3",
      "from": "ap_girls",
      "to": "girls_lap2",
      "latency": 5,
      "type": "wireless"
    },
    {
      "id": "e-ap_girls-4",
      "from": "ap_girls",
      "to": "girls_smart1",
      "latency": 5,
      "type": "wireless"
    },
    {
      "id": "e-s0-ap_ab1",
      "from": "s0_college",
      "to": "ap_ab1",
      "latency": 2,
      "type": "copper_straight"
    },
    {
      "id": "e-ap_ab1-1",
      "from": "ap_ab1",
      "to": "ab1_pc1",
      "latency": 5,
      "type": "wireless"
    },
    {
      "id": "e-ap_ab1-2",
      "from": "ap_ab1",
      "to": "ab1_lap1",
      "latency": 5,
      "type": "wireless"
    },
    {
      "id": "e-ap_ab1-3",
      "from": "ap_ab1",
      "to": "ab1_pc2",
      "latency": 5,
      "type": "wireless"
    },
    {
      "id": "e-ap_ab1-4",
      "from": "ap_ab1",
      "to": "ab1_lap2",
      "latency": 5,
      "type": "wireless"
    },
    {
      "id": "e-s0-ap_ab2",
      "from": "s0_college",
      "to": "ap_ab2",
      "latency": 2,
      "type": "copper_straight"
    },
    {
      "id": "e-ap_ab2-1",
      "from": "ap_ab2",
      "to": "ab2_pc1",
      "latency": 5,
      "type": "wireless"
    },
    {
      "id": "e-ap_ab2-2",
      "from": "ap_ab2",
      "to": "ab2_lap1",
      "latency": 5,
      "type": "wireless"
    },
    {
      "id": "e-ap_ab2-3",
      "from": "ap_ab2",
      "to": "ab2_pc2",
      "latency": 5,
      "type": "wireless"
    },
    {
      "id": "e-ap_ab2-4",
      "from": "ap_ab2",
      "to": "ab2_lap2",
      "latency": 5,
      "type": "wireless"
    },
    {
      "id": "e-s0-ap_it",
      "from": "s0_college",
      "to": "ap_it",
      "latency": 2,
      "type": "copper_straight"
    },
    {
      "id": "e-ap_it-1",
      "from": "ap_it",
      "to": "it_pc1",
      "latency": 5,
      "type": "wireless"
    },
    {
      "id": "e-ap_it-2",
      "from": "ap_it",
      "to": "it_pc2",
      "latency": 5,
      "type": "wireless"
    },
    {
      "id": "e-ap_it-3",
      "from": "ap_it",
      "to": "it_lap1",
      "latency": 5,
      "type": "wireless"
    },
    {
      "id": "e-s0-ap_lib",
      "from": "s0_college",
      "to": "ap_lib",
      "latency": 2,
      "type": "copper_straight"
    },
    {
      "id": "e-ap_lib-1",
      "from": "ap_lib",
      "to": "lib_pc1",
      "latency": 5,
      "type": "wireless"
    },
    {
      "id": "e-ap_lib-2",
      "from": "ap_lib",
      "to": "lib_pc2",
      "latency": 5,
      "type": "wireless"
    },
    {
      "id": "e-s0-ap_dome",
      "from": "s0_college",
      "to": "ap_dome",
      "latency": 2,
      "type": "copper_straight"
    },
    {
      "id": "e-ap_dome-1",
      "from": "ap_dome",
      "to": "dome_lap1",
      "latency": 5,
      "type": "wireless"
    },
    {
      "id": "e-ap_dome-2",
      "from": "ap_dome",
      "to": "dome_pc1",
      "latency": 5,
      "type": "wireless"
    },
    {
      "id": "e-ap_dome-3",
      "from": "ap_dome",
      "to": "dome_pc2",
      "latency": 5,
      "type": "wireless"
    }
  ],
  "sourceId": "main_router",
  "destinationIds": [
    "server_email",
    "server_dns",
    "server_web",
    "boys_pc1",
    "boys_lap1",
    "boys_lap2",
    "boys_smart1",
    "girls_pc1",
    "girls_lap1",
    "girls_lap2",
    "girls_smart1",
    "ab1_pc1",
    "ab1_lap1",
    "ab1_pc2",
    "ab1_lap2",
    "ab2_pc1",
    "ab2_lap1",
    "ab2_pc2",
    "ab2_lap2",
    "it_pc1",
    "it_pc2",
    "it_lap1",
    "lib_pc1",
    "lib_pc2",
    "dome_lap1",
    "dome_pc1",
    "dome_pc2"
  ],
  "width": 2900,
  "height": 1300
};
