version: "3.8"

services:
  vite-app:
    build: .
    container_name: vite-container
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    stdin_open: true
    tty: true